# Generated by Django 2.0 on 2018-11-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='show_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_image', models.ImageField(blank=True, upload_to='pics')),
            ],
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
